python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py
python3 war.py